### ISSUE TITLE
Person class

### ISSUE THREAD

**Issue by jasonren5** [CSE237SP2021/project-banking-app#2]
Fields
- private String firstName
  - Should be included as parameter in constructor
- private String lastName
  - Should be included as parameter in constructor
- private ArrayList<Account> accounts
  - Should NOT be included as parameter in constructor
  - OK to initialize as empty

Methods
- boolean addAccount()
  - should add a new account to the accounts ArrayList
  - return true if successful, false if not (could also declare this as void?)
- ArrayList<Account> getAccounts()
  - return accounts ArrayList

**Comment by cornellt** [comment]
Done for Iteration 1
